-- ══════════════════════════════════════════════════════════════════
-- FASE 2b · CATÁLOGOS DESDE EL EXCEL DE CODIFICACIÓN
--
-- Las curvas de tallas y los criterios de Kukos dejan de ser listas fijas en el código
-- y pasan a ser datos. El formulario de producto los lee de aquí: al elegir el tipo de
-- inventario, las tallas que ofrece salen de `tipos_inventario.tallas`.
--
-- Fuente: ARCHIVO PARA CODIFICACIÓN NUEVA ANTONIA.xlsx, hojas 'LISTAS', 'TIPO DE INV.'
-- y 'BASE DE DATOS CRITERIOS'. Idempotente: se puede volver a correr.
-- ══════════════════════════════════════════════════════════════════

BEGIN;

-- ─── Tipos de inventario con su curva de tallas ───────────────────
INSERT INTO public.tipos_inventario (codigo, nombre, tallas) VALUES
  ('INV001', 'INVENTARIO NUMERICO', ARRAY['U', '26', '28', '30', '32', '34', '36', '38', '40', '42', '44', '46', '48']),
  ('INV002', 'INVENTARIO ALFANUMERICO', ARRAY['U', 'XXS', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL', '7XL']),
  ('INV003', 'INVENTARIO JUNIOR-NIÑA-NIÑO', ARRAY['U', '2', '4', '6', '8', '10', '12', '14', '16', '18']),
  ('INV004', 'INVENTARIO BEBES', ARRAY['U', '0-0', '0-3', '3-6', '6-12', '12-18', '18-24', '24-36']),
  ('INV005', 'INVENTARIO MEDIAS', ARRAY['U', '0-2', '2-4', '4-6', '6-8', '8-10', '9-11', '10-12', '11-13', '12-14', '14-16'])
ON CONFLICT (codigo) DO UPDATE
  SET nombre = EXCLUDED.nombre, tallas = EXCLUDED.tallas;

-- ─── Criterios Kukos ──────────────────────────────────────────────
-- El grupo sale del primer dígito del código: 2 línea · 5 género · 7 componente
-- · 8 silueta · 9 uso. El código guarda el texto completo ('2003-PIJAMAS') porque es
-- lo que Kukos espera en el archivo de exportación.
INSERT INTO public.criterios_kukos (grupo, codigo, nombre) VALUES
  ('linea', '2001-BRASIER', 'BRASIER'),
  ('linea', '2002-PANTY', 'PANTY'),
  ('linea', '2003-PIJAMAS', 'PIJAMAS'),
  ('linea', '2004-VESTIDOS DE BANO', 'VESTIDOS DE BANO'),
  ('linea', '2004-VESTIDOSDEBANO', 'VESTIDOSDEBANO'),
  ('linea', '2005-MEDIAS', 'MEDIAS'),
  ('linea', '2006-BOXER', 'BOXER'),
  ('linea', '2007-PANTALONCILLO', 'PANTALONCILLO'),
  ('linea', '2008-FAJAS', 'FAJAS'),
  ('linea', '2009-ENAGUAS', 'ENAGUAS'),
  ('linea', '2010-BODYS', 'BODYS'),
  ('linea', '2011-PRODUCTOS FRIOS', 'PRODUCTOS FRIOS'),
  ('linea', '2012-CONJUNTOS ROPA INTERIOR', 'CONJUNTOS ROPA INTERIOR'),
  ('linea', '2012-CONJUNTOSROPAINTERIOR', 'CONJUNTOSROPAINTERIOR'),
  ('linea', '2013-CONJUNTOS ROPA EXTERIOR', 'CONJUNTOS ROPA EXTERIOR'),
  ('linea', '2013-CONJUNTOSROPAEXTERIOR', 'CONJUNTOSROPAEXTERIOR'),
  ('linea', '2014-TRIOS', 'TRIOS'),
  ('linea', '2015-SALIDAS DE BANO', 'SALIDAS DE BANO'),
  ('linea', '2015-SALIDASDEBANO', 'SALIDASDEBANO'),
  ('linea', '2016-DEPORTIVOS', 'DEPORTIVOS'),
  ('linea', '2017-SILICONA', 'SILICONA'),
  ('linea', '2018-CARGADERAS', 'CARGADERAS'),
  ('linea', '2019-EXTENSORES', 'EXTENSORES'),
  ('linea', '2020-ALMOHADILLAS', 'ALMOHADILLAS'),
  ('linea', '2021-PLANTILLAS', 'PLANTILLAS'),
  ('linea', '2022-AUTOADHESIVO', 'AUTOADHESIVO'),
  ('linea', '2023-COMBINACIONES', 'COMBINACIONES'),
  ('linea', '2024-PAQUETES', 'PAQUETES'),
  ('linea', '2025-ACCESORIOS', 'ACCESORIOS'),
  ('linea', '2026-COSMETICOS', 'COSMETICOS'),
  ('linea', '2027-BIENESTAR', 'BIENESTAR'),
  ('linea', '2028-BUSTIER', 'BUSTIER'),
  ('linea', '2029-ACEITES CORPORALES', 'ACEITES CORPORALES'),
  ('linea', '2030-CAPILAR', 'CAPILAR'),
  ('linea', '2031-CUIDADO PERSONAL', 'CUIDADO PERSONAL'),
  ('linea', '2032-BOLSOS', 'BOLSOS'),
  ('linea', '2033-JEANS', 'JEANS'),
  ('linea', '2034-CAMISETAS', 'CAMISETAS'),
  ('linea', '2035-VESTIDOS', 'VESTIDOS'),
  ('linea', '2036-SHORT', 'SHORT'),
  ('linea', '2037-BLUSAS', 'BLUSAS'),
  ('linea', '2038-DISFRAZ', 'DISFRAZ'),
  ('linea', '2039-HOGAR', 'HOGAR'),
  ('linea', '2040-LINEA MEDICA', 'LINEA MEDICA'),
  ('linea', '2040-LINEAMEDICA', 'LINEAMEDICA'),
  ('linea', '2041-TARRO DE LA SUERTE KUKO SUERTE', 'TARRO DE LA SUERTE KUKO SUERTE'),
  ('linea', '2042-PANTALONETAS', 'PANTALONETAS'),
  ('linea', '2043-CHAQUETAS', 'CHAQUETAS'),
  ('linea', '2044-PANTALON', 'PANTALON'),
  ('linea', '2045-CAMISAS', 'CAMISAS'),
  ('linea', '2046-FALDAS', 'FALDAS'),
  ('linea', '2047-PANUELOS', 'PANUELOS'),
  ('linea', '2048-BUSOS', 'BUSOS'),
  ('linea', '2049-BICICLETERO', 'BICICLETERO'),
  ('linea', '2051-SUDADERAS', 'SUDADERAS'),
  ('linea', '2052-BABBYDOLL', 'BABBYDOLL'),
  ('linea', '2053-BRASIERDUO', 'BRASIERDUO'),
  ('linea', '2054-BRALETTE', 'BRALETTE'),
  ('linea', '2055-LEGGINS', 'LEGGINS'),
  ('linea', '2056-CONJUNTO BRALETE', 'CONJUNTO BRALETE'),
  ('linea', '2065-LIGUERO', 'LIGUERO'),
  ('linea', '2066-KIS DE ACCESORIOS', 'KIS DE ACCESORIOS'),
  ('linea', '2067-CORSET', 'CORSET'),
  ('linea', '2068-TOP', 'TOP'),
  ('linea', '2070-PAQUETE-MEDIAS', 'PAQUETE-MEDIAS'),
  ('linea', '2071-DUO TOP', 'DUO TOP'),
  ('linea', '2073-TRIO TOP', 'TRIO TOP'),
  ('linea', '2501-INGRESO PROPIO', 'INGRESO PROPIO'),
  ('linea', '2502-CONCESIONES', 'CONCESIONES'),
  ('linea', '2503-SERVICIOS', 'SERVICIOS'),
  ('linea', '2998-SERVICIOS', 'SERVICIOS'),
  ('genero', '5001-DAMA', 'DAMA'),
  ('genero', '5002-HOMBRE', 'HOMBRE'),
  ('genero', '5003-JUNIOR', 'JUNIOR'),
  ('genero', '5004-NINA', 'NINA'),
  ('genero', '5005-NINO', 'NINO'),
  ('genero', '5006-INFANTIL', 'INFANTIL'),
  ('genero', '5007-BEBE', 'BEBE'),
  ('genero', '5008-UNISEXO', 'UNISEXO'),
  ('genero', '5009-PREMIOS', 'PREMIOS'),
  ('genero', '5998-SERVICIOS', 'SERVICIOS'),
  ('componente', '7001-SPANDEX NYLON', 'SPANDEX NYLON'),
  ('componente', '7002-SPANDEX ALGODON', 'SPANDEX ALGODON'),
  ('componente', '7003-POLIESTER', 'POLIESTER'),
  ('componente', '7004-ENCAJE', 'ENCAJE'),
  ('componente', '7005-TULL', 'TULL'),
  ('componente', '7006-TULL LYCRA', 'TULL LYCRA'),
  ('componente', '7007-JACQUARD', 'JACQUARD'),
  ('componente', '7008-MICROFIBRA', 'MICROFIBRA'),
  ('componente', '7009-BORDADO', 'BORDADO'),
  ('componente', '7010-DOBLE PUSH UP', 'DOBLE PUSH UP'),
  ('componente', '7011-POWERNET', 'POWERNET'),
  ('componente', '7012-SIMPLEX', 'SIMPLEX'),
  ('componente', '7013-LATEX', 'LATEX'),
  ('componente', '7014-SILICONA', 'SILICONA'),
  ('componente', '7015-SPANDEX', 'SPANDEX'),
  ('componente', '7016-COSMETICOS', 'COSMETICOS'),
  ('componente', '7017-PREMIOS', 'PREMIOS'),
  ('componente', '7018-MAYATEX', 'MAYATEX'),
  ('componente', '7019-POLIETILENO', 'POLIETILENO'),
  ('componente', '7020-ADHESIVOS', 'ADHESIVOS'),
  ('componente', '7021-GEL', 'GEL'),
  ('componente', '7022-FRIOS', 'FRIOS'),
  ('componente', '7023-ALGODON', 'ALGODON'),
  ('componente', '7024-PAD DE AIRE', 'PAD DE AIRE'),
  ('componente', '7025-POLIAMIDA ELASTANO', 'POLIAMIDA ELASTANO'),
  ('componente', '7026-DOBLE PUNTO', 'DOBLE PUNTO'),
  ('componente', '7027-SPANDEX POLIESTER', 'SPANDEX POLIESTER'),
  ('componente', '7028-NYLON SIMPLEX', 'NYLON SIMPLEX'),
  ('componente', '7029-CARTON PROCESADO', 'CARTON PROCESADO'),
  ('componente', '7030-GASA', 'GASA'),
  ('componente', '7031-BIENESTAR', 'BIENESTAR'),
  ('componente', '7032-FELPA', 'FELPA'),
  ('componente', '7033-ALUMINIO', 'ALUMINIO'),
  ('componente', '7034-TEJIDO PLANO', 'TEJIDO PLANO'),
  ('componente', '7035-MALLA', 'MALLA'),
  ('componente', '7036-VELVETIN', 'VELVETIN'),
  ('componente', '7037-VISCOSA', 'VISCOSA'),
  ('componente', '7042-SATIN', 'SATIN'),
  ('componente', '7043-POLIESTER ALGODÓN', 'POLIESTER ALGODÓN'),
  ('componente', '7044-BLONDA', 'BLONDA'),
  ('componente', '7045-SHIFON', 'SHIFON'),
  ('componente', '7998-SERVICIOS', 'SERVICIOS'),
  ('silueta', '8001-MAGIC', 'MAGIC'),
  ('silueta', '8002-REALCE', 'REALCE'),
  ('silueta', '8003-AVIONETO', 'AVIONETO'),
  ('silueta', '8004-SENORERO', 'SENORERO'),
  ('silueta', '8005-MATERNO', 'MATERNO'),
  ('silueta', '8006-PRINCIPIANTE', 'PRINCIPIANTE'),
  ('silueta', '8007-TOP', 'TOP'),
  ('silueta', '8008-CORSELETE', 'CORSELETE'),
  ('silueta', '8009-STRAPLE', 'STRAPLE'),
  ('silueta', '8010-DUO', 'DUO'),
  ('silueta', '8011-HILO', 'HILO'),
  ('silueta', '8012-BLOQUE', 'BLOQUE'),
  ('silueta', '8013-BRASILERA', 'BRASILERA'),
  ('silueta', '8014-SEMITANGA', 'SEMITANGA'),
  ('silueta', '8015-TANGA', 'TANGA'),
  ('silueta', '8016-BIKINI', 'BIKINI'),
  ('silueta', '8017-BALCONET', 'BALCONET'),
  ('silueta', '8018-REALCE NATURAL', 'REALCE NATURAL'),
  ('silueta', '8019-CACHETERO', 'CACHETERO'),
  ('silueta', '8020-CLASICO SENORERO', 'CLASICO SENORERO'),
  ('silueta', '8021-PANTY LEVANTACOLA', 'PANTY LEVANTACOLA'),
  ('silueta', '8022-PANTY MATERNO', 'PANTY MATERNO'),
  ('silueta', '8023-PANTY FAJA', 'PANTY FAJA'),
  ('silueta', '8024-SIN COSTURA', 'SIN COSTURA'),
  ('silueta', '8025-PANTALONCILLOS', 'PANTALONCILLOS'),
  ('silueta', '8026-PANTYFLEX', 'PANTYFLEX'),
  ('silueta', '8027-ZAPATILLA', 'ZAPATILLA'),
  ('silueta', '8028-FALDA LIGUERO', 'FALDA LIGUERO'),
  ('silueta', '8029-VELADA', 'VELADA'),
  ('silueta', '8030-SUPERVELADA', 'SUPERVELADA'),
  ('silueta', '8031-DESCANSO', 'DESCANSO'),
  ('silueta', '8032-DEDOS LIBRES', 'DEDOS LIBRES'),
  ('silueta', '8033-MAYA', 'MAYA'),
  ('silueta', '8034-SEDA FRIA', 'SEDA FRIA'),
  ('silueta', '8035-VARICE', 'VARICE'),
  ('silueta', '8036-EJECUTIVA', 'EJECUTIVA'),
  ('silueta', '8037-CALCETINES', 'CALCETINES'),
  ('silueta', '8038-TALONERAS', 'TALONERAS'),
  ('silueta', '8039-LIGAS', 'LIGAS'),
  ('silueta', '8040-LIGUEROS', 'LIGUEROS'),
  ('silueta', '8041-CLASICA', 'CLASICA'),
  ('silueta', '8042-MEDIA PANTALON', 'MEDIA PANTALON'),
  ('silueta', '8043-MEDIA SLACK', 'MEDIA SLACK'),
  ('silueta', '8044-CASUAL', 'CASUAL'),
  ('silueta', '8045-LEGGINS', 'LEGGINS'),
  ('silueta', '8046-COLEGIAL', 'COLEGIAL'),
  ('silueta', '8047-DEPORTIVO', 'DEPORTIVO'),
  ('silueta', '8048-PRODUCTOS FRIOS', 'PRODUCTOS FRIOS'),
  ('silueta', '8049-LEVANTACOLA', 'LEVANTACOLA'),
  ('silueta', '8050-REDUCTOR', 'REDUCTOR'),
  ('silueta', '8051-PANTALON LARGO', 'PANTALON LARGO'),
  ('silueta', '8052-PANTALON CORTO', 'PANTALON CORTO'),
  ('silueta', '8053-PANTALON CAPRI', 'PANTALON CAPRI'),
  ('silueta', '8054-BATOLA TIRA', 'BATOLA TIRA'),
  ('silueta', '8055-BATOLA SISA', 'BATOLA SISA'),
  ('silueta', '8056-BATOLA MANGA', 'BATOLA MANGA'),
  ('silueta', '8057-SENORERA MANGA CORTA', 'SENORERA MANGA CORTA'),
  ('silueta', '8058-SENORERA MANGA SISA', 'SENORERA MANGA SISA'),
  ('silueta', '8059-CAMISA MANGA CORTA', 'CAMISA MANGA CORTA'),
  ('silueta', '8060-CAMISA MANGA SISA', 'CAMISA MANGA SISA'),
  ('silueta', '8061-ESQUELETO', 'ESQUELETO'),
  ('silueta', '8062-BABY DOLL', 'BABY DOLL'),
  ('silueta', '8063-BOBITO', 'BOBITO'),
  ('silueta', '8064-ENTERIZO', 'ENTERIZO'),
  ('silueta', '8065-TORERO', 'TORERO'),
  ('silueta', '8066-DOS PIEZAS', 'DOS PIEZAS'),
  ('silueta', '8067-TRES PIEZAS', 'TRES PIEZAS'),
  ('silueta', '8068-TANKINI', 'TANKINI'),
  ('silueta', '8069-ENTERO', 'ENTERO'),
  ('silueta', '8070-TRIKINI', 'TRIKINI'),
  ('silueta', '8071-GORROS', 'GORROS'),
  ('silueta', '8072-FALDA', 'FALDA'),
  ('silueta', '8073-VESTIDO', 'VESTIDO'),
  ('silueta', '8074-PAREO', 'PAREO'),
  ('silueta', '8075-SHORT', 'SHORT'),
  ('silueta', '8076-CINTURILLA', 'CINTURILLA'),
  ('silueta', '8077-TERMICA', 'TERMICA'),
  ('silueta', '8078-YESO', 'YESO'),
  ('silueta', '8079-MODELADORAS', 'MODELADORAS'),
  ('silueta', '8080-REDUCTORAS', 'REDUCTORAS'),
  ('silueta', '8081-CHALECO', 'CHALECO'),
  ('silueta', '8082-INVISIBLE', 'INVISIBLE'),
  ('silueta', '8083-TAPAPEZON', 'TAPAPEZON'),
  ('silueta', '8084-MUÑEQUERA', 'MUÑEQUERA'),
  ('silueta', '8085-PANTALONETAS DE BANO', 'PANTALONETAS DE BANO'),
  ('silueta', '8086-DISFRAZ', 'DISFRAZ'),
  ('silueta', '8087-ACEITES', 'ACEITES'),
  ('silueta', '8088-LABIAL', 'LABIAL'),
  ('silueta', '8089-CREMAS DE MANOS', 'CREMAS DE MANOS'),
  ('silueta', '8090-DELINEADOR', 'DELINEADOR'),
  ('silueta', '8091-PESTANINA', 'PESTANINA'),
  ('silueta', '8092-GEL', 'GEL'),
  ('silueta', '8093-CREMA EXFOLIANTE', 'CREMA EXFOLIANTE'),
  ('silueta', '8094-GEL REAFIRMANTE DE BUSTO', 'GEL REAFIRMANTE DE BUSTO'),
  ('silueta', '8095-CREMA REAFIRMANTE', 'CREMA REAFIRMANTE'),
  ('silueta', '8096-CREMA CONTROL CELULITIS', 'CREMA CONTROL CELULITIS'),
  ('silueta', '8097-GEL REDUCTOR', 'GEL REDUCTOR'),
  ('silueta', '8098-CREMA CONTROL ESTRIAS', 'CREMA CONTROL ESTRIAS'),
  ('silueta', '8099-ACEITE INTIMO', 'ACEITE INTIMO'),
  ('silueta', '8100-JABON INTIMO', 'JABON INTIMO'),
  ('silueta', '8101-GEL ANTIBACTERIAL', 'GEL ANTIBACTERIAL'),
  ('silueta', '8102-TRATAMIENTO CAPILAR', 'TRATAMIENTO CAPILAR'),
  ('silueta', '8103-LUBRICANTE INTIMO', 'LUBRICANTE INTIMO'),
  ('silueta', '8104-MASAJEADOR', 'MASAJEADOR'),
  ('silueta', '8105-BLANQUEADOR', 'BLANQUEADOR'),
  ('silueta', '8106-CORRECTOR DE JUANETE', 'CORRECTOR DE JUANETE'),
  ('silueta', '8107-CORRECTOR DE POSTURA', 'CORRECTOR DE POSTURA'),
  ('silueta', '8108-CINTURON PROTECTOR COLUMNA', 'CINTURON PROTECTOR COLUMNA'),
  ('silueta', '8109-COREECTOR DE COLUMNA', 'COREECTOR DE COLUMNA'),
  ('silueta', '8110-CAMISILLAS', 'CAMISILLAS'),
  ('silueta', '8111-PROTESIS MAMARIA', 'PROTESIS MAMARIA'),
  ('silueta', '8112-SPLASH', 'SPLASH'),
  ('silueta', '8113-LOCION', 'LOCION'),
  ('silueta', '8114-JABON', 'JABON'),
  ('silueta', '8115-LOCION / CREMA', 'LOCION / CREMA'),
  ('silueta', '8116-JABON / CREMA', 'JABON / CREMA'),
  ('silueta', '8117-BLANQUEADOR DENTAL', 'BLANQUEADOR DENTAL'),
  ('silueta', '8118-CORTINAS', 'CORTINAS'),
  ('silueta', '8119-MANTELES', 'MANTELES'),
  ('silueta', '8120-CENEFAS', 'CENEFAS'),
  ('silueta', '8121-TOALLAS', 'TOALLAS'),
  ('silueta', '8122-DETERGENTE', 'DETERGENTE'),
  ('silueta', '8123-ESTANDARTE', 'ESTANDARTE'),
  ('silueta', '8124-SABANAS', 'SABANAS'),
  ('silueta', '8125-KIT MESA', 'KIT MESA'),
  ('silueta', '8126-ELECTRODOMESTICOS', 'ELECTRODOMESTICOS'),
  ('silueta', '8127-NAVIDAD', 'NAVIDAD'),
  ('silueta', '8128-COCINA', 'COCINA'),
  ('silueta', '8129-TECNOLOGIA', 'TECNOLOGIA'),
  ('silueta', '8130-TE', 'TE'),
  ('silueta', '8131-JABONES', 'JABONES'),
  ('silueta', '8132-SHAMPOO', 'SHAMPOO'),
  ('silueta', '8133-ACONDICIONADOR', 'ACONDICIONADOR'),
  ('silueta', '8134-ESPUMA DENTAL', 'ESPUMA DENTAL'),
  ('silueta', '8135-DESINFECTANTE', 'DESINFECTANTE'),
  ('silueta', '8136-ORGANIZADORES', 'ORGANIZADORES'),
  ('silueta', '8137-BOXER LARGO', 'BOXER LARGO'),
  ('silueta', '8138-BOXER CORTO', 'BOXER CORTO'),
  ('silueta', '8139-BLUSA BASICA', 'BLUSA BASICA'),
  ('silueta', '8140-BLUSA CUELLO V', 'BLUSA CUELLO V'),
  ('silueta', '8141-BLUSA TIRAS', 'BLUSA TIRAS'),
  ('silueta', '8142-CAMISETA POLO', 'CAMISETA POLO'),
  ('silueta', '8143-BOLSOS', 'BOLSOS'),
  ('silueta', '8144-CAMIBUSO', 'CAMIBUSO'),
  ('silueta', '8145-CAMISETA MANGA CORTA', 'CAMISETA MANGA CORTA'),
  ('silueta', '8146-BLUSA MANGA SISA', 'BLUSA MANGA SISA'),
  ('silueta', '8147-CARGADERA 6 MM', 'CARGADERA 6 MM'),
  ('silueta', '8148-CARGADERA 10 MM', 'CARGADERA 10 MM'),
  ('silueta', '8149-CARGADERA 13 MM', 'CARGADERA 13 MM'),
  ('silueta', '8150-CARGADERA 16 MM', 'CARGADERA 16 MM'),
  ('silueta', '8151-CARGADERA 20 MM', 'CARGADERA 20 MM'),
  ('silueta', '8152-EXTENSOR 2X3', 'EXTENSOR 2X3'),
  ('silueta', '8153-EXTENSOR 3X2', 'EXTENSOR 3X2'),
  ('silueta', '8154-EXTENSOR 3X3', 'EXTENSOR 3X3'),
  ('silueta', '8155-EXTENSOR 4X3', 'EXTENSOR 4X3'),
  ('silueta', '8156-EXTENSOR 5X3', 'EXTENSOR 5X3'),
  ('silueta', '8157-EXTENSOR 6X3', 'EXTENSOR 6X3'),
  ('silueta', '8158-ALMOHADILLA', 'ALMOHADILLA'),
  ('silueta', '8159-BLUSON', 'BLUSON'),
  ('silueta', '8160-ACCESORIO PARA BRASIER', 'ACCESORIO PARA BRASIER'),
  ('silueta', '8161-CARGADERA ARANA', 'CARGADERA ARANA'),
  ('silueta', '8162-TARRO DE LA SUERTE KUKO SUERTE', 'TARRO DE LA SUERTE KUKO SUERTE'),
  ('silueta', '8163-SILICONA', 'SILICONA'),
  ('silueta', '8164-FALDA LARGA', 'FALDA LARGA'),
  ('silueta', '8165-FALDA CORTA', 'FALDA CORTA'),
  ('silueta', '8166-CARGADERA MARIPOSA', 'CARGADERA MARIPOSA'),
  ('silueta', '8167-ENAGUAS', 'ENAGUAS'),
  ('silueta', '8168-BLOQUEADOR', 'BLOQUEADOR'),
  ('silueta', '8169-BODY SENOS LIBRES', 'BODY SENOS LIBRES'),
  ('silueta', '8170-CAMISETA MANGA LARGA', 'CAMISETA MANGA LARGA'),
  ('silueta', '8171-AUTOADHESIVO', 'AUTOADHESIVO'),
  ('silueta', '8172-PLANTILLAS', 'PLANTILLAS'),
  ('silueta', '8173-BATOLA STRAPLE', 'BATOLA STRAPLE'),
  ('silueta', '8174-KIMONO', 'KIMONO'),
  ('silueta', '8175-BUSTIER', 'BUSTIER'),
  ('silueta', '8176-BRALETE', 'BRALETE'),
  ('silueta', '8177-COJIN', 'COJIN'),
  ('silueta', '8178-MULTIUSOS', 'MULTIUSOS'),
  ('silueta', '8179-CLASICO NINA', 'CLASICO NINA'),
  ('silueta', '8180-PUNTERA', 'PUNTERA'),
  ('silueta', '8181-TABLA ABDOMINAL', 'TABLA ABDOMINAL'),
  ('silueta', '8182-POLVO', 'POLVO'),
  ('silueta', '8183-BASE MAQUILLAJE', 'BASE MAQUILLAJE'),
  ('silueta', '8184-CORRECTOR DE MAQUILLAJE', 'CORRECTOR DE MAQUILLAJE'),
  ('silueta', '8185-BRILLO', 'BRILLO'),
  ('silueta', '8186-RUBOR', 'RUBOR'),
  ('silueta', '8187-REMOVEDOR', 'REMOVEDOR'),
  ('silueta', '8188-BASE DE UÑAS', 'BASE DE UÑAS'),
  ('silueta', '8189-ESMALTE', 'ESMALTE'),
  ('silueta', '8190-EDREDON', 'EDREDON'),
  ('silueta', '8191-CALCETAS', 'CALCETAS'),
  ('silueta', '8192-PORTA CARGADERAS', 'PORTA CARGADERAS'),
  ('silueta', '8193-CHAQUETA', 'CHAQUETA'),
  ('silueta', '8194-LECHE LIMPIADORA FACIAL', 'LECHE LIMPIADORA FACIAL'),
  ('silueta', '8195-LOCION TONICO ASTRIGENTE', 'LOCION TONICO ASTRIGENTE'),
  ('silueta', '8196-CREMA FACIAL HUMECTANTE', 'CREMA FACIAL HUMECTANTE'),
  ('silueta', '8199-CARGADERA 7 MM', 'CARGADERA 7 MM'),
  ('silueta', '8200-CARGADERA PITILLO', 'CARGADERA PITILLO'),
  ('silueta', '8201-EXTENSOR 3X4', 'EXTENSOR 3X4'),
  ('silueta', '8205-BUSO', 'BUSO'),
  ('silueta', '8211-PANTY SEÑORERO', 'PANTY SEÑORERO'),
  ('silueta', '8212-BODY', 'BODY'),
  ('silueta', '8213-PANTY REDUCTOR', 'PANTY REDUCTOR'),
  ('silueta', '8214-BOXER MEDIANO', 'BOXER MEDIANO'),
  ('silueta', '8215-EXTENSOR RESORTE 3X2', 'EXTENSOR RESORTE 3X2'),
  ('silueta', '8216-EXTENSOR RESORTE 3X3', 'EXTENSOR RESORTE 3X3'),
  ('silueta', '8217-KIT ACCESORIOS CARGADERA TAPA PEZON EXTEN', 'KIT ACCESORIOS CARGADERA TAPA PEZON EXTEN'),
  ('silueta', '8218-BLUSON ABIERTO', 'BLUSON ABIERTO'),
  ('silueta', '8219-CORSET', 'CORSET'),
  ('silueta', '8220-TAPABOCAS', 'TAPABOCAS'),
  ('silueta', '8221-TRIANGULAR', 'TRIANGULAR'),
  ('silueta', '8222-PAQUETE X 5', 'PAQUETE X 5'),
  ('silueta', '8223-PAQUETE X 7', 'PAQUETE X 7'),
  ('silueta', '8224-5 PIEZAS', '5 PIEZAS'),
  ('silueta', '8225-CICLISTA', 'CICLISTA'),
  ('silueta', '8226-EXTENSOR 8X3', 'EXTENSOR 8X3'),
  ('silueta', '8227-ESTENSOR RESORTE 8X2', 'ESTENSOR RESORTE 8X2'),
  ('silueta', '8228-EXTENSOR RESORTE 6X2', 'EXTENSOR RESORTE 6X2'),
  ('silueta', '8229-PANTALONETA CORTA', 'PANTALONETA CORTA'),
  ('silueta', '8230-PANTALONETA LARGA', 'PANTALONETA LARGA'),
  ('silueta', '8231-BRASILERA PX3', 'BRASILERA PX3'),
  ('silueta', '8232-BOXER CORTO PX2', 'BOXER CORTO PX2'),
  ('silueta', '8233-BOXER CORTO PX3', 'BOXER CORTO PX3'),
  ('silueta', '8234-BOXER CORTO PX5', 'BOXER CORTO PX5'),
  ('silueta', '8235-BOXER CORTO PX7', 'BOXER CORTO PX7'),
  ('silueta', '8236-BOXER LARGO PX2', 'BOXER LARGO PX2'),
  ('silueta', '8237-BOXER LARGO PX3', 'BOXER LARGO PX3'),
  ('silueta', '8238-BOXER LARGO PX5', 'BOXER LARGO PX5'),
  ('silueta', '8239-BOXER LARGO PX7', 'BOXER LARGO PX7'),
  ('silueta', '8240-BRALETTE PX2', 'BRALETTE PX2'),
  ('silueta', '8241-BRALETTE PX3', 'BRALETTE PX3'),
  ('silueta', '8242-BRALETTE PX5', 'BRALETTE PX5'),
  ('silueta', '8243-BRALETTE PX7', 'BRALETTE PX7'),
  ('silueta', '8244-BRASILERA PX2', 'BRASILERA PX2'),
  ('silueta', '8245-BRASILERA PX5', 'BRASILERA PX5'),
  ('silueta', '8246-BRASILERA PX7', 'BRASILERA PX7'),
  ('silueta', '8247-CACHETERO PX2', 'CACHETERO PX2'),
  ('silueta', '8248-CACHETERO PX3', 'CACHETERO PX3'),
  ('silueta', '8249-CACHETERO PX5', 'CACHETERO PX5'),
  ('silueta', '8250-CACHETERO PX7', 'CACHETERO PX7'),
  ('silueta', '8251-CALCETAS PX2', 'CALCETAS PX2'),
  ('silueta', '8252-CALCETAS PX3', 'CALCETAS PX3'),
  ('silueta', '8253-CALCETAS PX5', 'CALCETAS PX5'),
  ('silueta', '8254-CALCETAS PX7', 'CALCETAS PX7'),
  ('silueta', '8255-CALCETINES PX2', 'CALCETINES PX2'),
  ('silueta', '8256-CALCETINES PX3', 'CALCETINES PX3'),
  ('silueta', '8257-CALCETINES PX5', 'CALCETINES PX5'),
  ('silueta', '8258-CALCETINES PX7', 'CALCETINES PX7'),
  ('silueta', '8259-DEPORTIVO PX2', 'DEPORTIVO PX2'),
  ('silueta', '8260-DEPORTIVO PX3', 'DEPORTIVO PX3'),
  ('silueta', '8261-DEPORTIVO PX7', 'DEPORTIVO PX7'),
  ('silueta', '8262-DEPORTIVO PX5', 'DEPORTIVO PX5'),
  ('silueta', '8263-HILO PX2', 'HILO PX2'),
  ('silueta', '8264-HILO PX3', 'HILO PX3'),
  ('silueta', '8265-HILO PX5', 'HILO PX5'),
  ('silueta', '8266-HILO PX7', 'HILO PX7'),
  ('silueta', '8267-PANTYFLEX PX2', 'PANTYFLEX PX2'),
  ('silueta', '8268-PANTYFLEX PX3', 'PANTYFLEX PX3'),
  ('silueta', '8269-PANTYFLEX PX5', 'PANTYFLEX PX5'),
  ('silueta', '8270-PANTYFLEX PX7', 'PANTYFLEX PX7'),
  ('silueta', '8271-REALCE NATURAL PX2', 'REALCE NATURAL PX2'),
  ('silueta', '8272-REALCE NATURAL PX3', 'REALCE NATURAL PX3'),
  ('silueta', '8273-REALCE NATURAL PX5', 'REALCE NATURAL PX5'),
  ('silueta', '8274-REALCE NATURAL PX7', 'REALCE NATURAL PX7'),
  ('silueta', '8275-REALCE PX2', 'REALCE PX2'),
  ('silueta', '8276-REALCE PX3', 'REALCE PX3'),
  ('silueta', '8277-REALCE PX5', 'REALCE PX5'),
  ('silueta', '8278-REALCE PX7', 'REALCE PX7'),
  ('silueta', '8279-SEMITANGA PX2', 'SEMITANGA PX2'),
  ('silueta', '8280-SEMITANGA PX3', 'SEMITANGA PX3'),
  ('silueta', '8281-SEMITANGA PX5', 'SEMITANGA PX5'),
  ('silueta', '8282-SEÑORERO PX2', 'SEÑORERO PX2'),
  ('silueta', '8283-SEÑORERO PX3', 'SEÑORERO PX3'),
  ('silueta', '8284-SEÑORERO PX5', 'SEÑORERO PX5'),
  ('silueta', '8285-SEÑORERO PX7', 'SEÑORERO PX7'),
  ('silueta', '8286-SIN COSTURA PX2', 'SIN COSTURA PX2'),
  ('silueta', '8287-SIN COSTURA PX3', 'SIN COSTURA PX3'),
  ('silueta', '8288-SIN COSTURA PX5', 'SIN COSTURA PX5'),
  ('silueta', '8289-SIN COSTURA PX7', 'SIN COSTURA PX7'),
  ('silueta', '8290-TALONERAS PX2', 'TALONERAS PX2'),
  ('silueta', '8291-TALONERAS PX3', 'TALONERAS PX3'),
  ('silueta', '8292-TALONERAS PX5', 'TALONERAS PX5'),
  ('silueta', '8293-TALONERAS PX7', 'TALONERAS PX7'),
  ('silueta', '8294-TANGA PX2', 'TANGA PX2'),
  ('silueta', '8295-TANGA PX3', 'TANGA PX3'),
  ('silueta', '8296-TANGA PX5', 'TANGA PX5'),
  ('silueta', '8297-TANGA PX7', 'TANGA PX7'),
  ('silueta', '8298-MOLDEADORAS', 'MOLDEADORAS'),
  ('silueta', '8299-SEMITANGA PX7', 'SEMITANGA PX7'),
  ('silueta', '8998-SERVICIOS', 'SERVICIOS'),
  ('uso', '9001-ROPA INTERIOR', 'ROPA INTERIOR'),
  ('uso', '9002-ROPA EXTERIOR', 'ROPA EXTERIOR'),
  ('uso', '9003-BIENESTAR', 'BIENESTAR'),
  ('uso', '9004-PREMIOS', 'PREMIOS'),
  ('uso', '9501-FERIA', 'FERIA'),
  ('uso', '9502-MUJER LATINA', 'MUJER LATINA'),
  ('uso', '9503-SHER', 'SHER'),
  ('uso', '9504-CONCESION', 'CONCESION'),
  ('uso', '9505-NO APLICA PARA INFORME', 'NO APLICA PARA INFORME'),
  ('uso', '9998-SERVICIOS', 'SERVICIOS')
ON CONFLICT (grupo, codigo) DO UPDATE SET nombre = EXCLUDED.nombre;

-- ─── Comprobación ─────────────────────────────────────────────────
SELECT codigo, nombre, array_length(tallas,1) AS tallas FROM tipos_inventario ORDER BY codigo;
-- Esperado: INV001 13 · INV002 13 · INV003 10 · INV004 8 · INV005 11

SELECT grupo, count(*) AS opciones FROM criterios_kukos GROUP BY grupo ORDER BY grupo;
-- Esperado: componente 42 · genero 10 · linea 71 · silueta 290 · uso 10

COMMIT;

-- ROLLBACK:  DELETE FROM criterios_kukos;  DELETE FROM tipos_inventario;
